### ISSUE TITLE
Don't count cancelled requests into rate limit if they haven't been executed yet

### ISSUE THREAD

**Issue by olii** [aishek/axios-rate-limit#21]
First, I find this a great library.
My use-case is that I display a large table and for each row, there are 2 requests I need to make. The table uses pagination.
When I go to the next page I cancel all the unfinished requests from the previous page. The old requests don't need to be resolved since they are not going to be displayed, anyway.

I can clearly see that when I jump through the pages in the paginated table, the requests are getting delayed. The old (canceled) requests are getting executed in a "rate-limited" manner. They don't make it to the server but still, they are counted into rate limit. Once the old requests are all done, the new requests are resolved.
I think that this is not a correct behavior and canceled requests should be removed from the rate limiter, thus allowing the new requests getting executed faster.

Do you think that this has the potential to make the implementation of this library more robust?

**Comment by aishek** [comment]
Thanks, Oliver! I agree cancelled requests should not be used for limit calculations. I will update the library these holidays, also appreciate any help with it

**Comment by supermooshman** [comment]
@aishek any update on this?

**Comment by aishek** [comment]
[Published](https://github.com/aishek/axios-rate-limit/blob/master/CHANGELOG.md#131) in version `1.3.1`
