### ISSUE TITLE
Internal setTimeout causes the application to run until the perMilliseconds time is up

### ISSUE THREAD

**Issue by lpelorosso** [aishek/axios-rate-limit#32]
If you run this:

```
const http = rateLimit(axios.create(), { maxRequests: 4, perMilliseconds: 20000 })
http.get('http://localhost:4567/__sinatra__/404.png') 
http.get('http://localhost:4567/__sinatra__/404.png') 
http.get('http://localhost:4567/__sinatra__/404.png') 
```
It will perform the three requests, and then the application will continue running for 20 seconds until the internal timeout is up.

**Comment by aishek** [comment]
This is correct. It is expected behavior by design.

It could be better. And https://github.com/aishek/axios-rate-limit/pull/39/files solves the problem. I think about adopting the algorithm from there in future versions.
