### ISSUE TITLE
typescript typings issues

### ISSUE THREAD

**Issue by acao** [aishek/axios-rate-limit#33]
hey thanks for this great module!

quick note - the options for instantiating the module all show as required options, and also maxRPS is not present in the available options

so, for example, this fails with typescript:
```ts
const http = rateLimit(axios.create(), {
  maxRPS: parseInt(process.env.ENV_VARIABLE, 10) || 50,
})
```

because:

1. `maxRPS` is not an available option according to the typings
1. required values of `maxRequests` and `perMilliseconds` are not present

**Comment by acao** [comment]
was using an outdated version, my bad! looks like these issues are addressed in the latest release

i found a few other issues and created a PR here:

https://github.com/aishek/axios-rate-limit/pull/34

**Comment by aishek** [comment]
Merged and published in https://github.com/aishek/axios-rate-limit/releases/tag/1.3.2
