### ISSUE TITLE
Issue with the latest axios (v.1)

### ISSUE THREAD

**Issue by kingmaker-agm** [aishek/axios-rate-limit#57]
This library has used the `axios: ^0.18.0` as a **devDependency** to pull in the Axios while development.
- It has to be in the **dependency** section of the `package.json` to force relevant _Axios version_ constraint as well.  
  
```json
{
   "dependencies": {
      "axios": "^0.18.0",
   }
}
```

This way your package will not be installed in the **projects** using `axios: 1.13.0`.

> I used your library to solve the rate limiting Issue in our project, But wasted an entire day as I relied on **TS** to tell me there wasn't any Error. Found out the Issue doing **debugging** the runtime values.

**Comment by aishek** [comment]
Thank you for notice that! I've updated the spec to:

```
  "dependencies": {
    "axios": ">=0.18.0"
  },
```

Also I've added tests against both main versions of axois

https://github.com/aishek/axios-rate-limit/pull/72

**Comment by aishek** [comment]
Fix published in https://github.com/aishek/axios-rate-limit/releases/tag/1.3.3
